//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concesionario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modelos
    {
        public int ModeloId { get; set; }
        public int MarcaId { get; set; }
        public string Modelo { get; set; }
    }
}
